CREATE TABLE `t_ledger` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `RECEIPT_DATE` date DEFAULT NULL,
  `MEMBER_NAME` varchar(10) DEFAULT NULL,
  `CHECK_NUMBER` varchar(10) DEFAULT NULL,
  `CHECK_DATE` date DEFAULT NULL,
  `PAYMENT_TYPE` varchar(10) DEFAULT NULL,
  `DEPOSIT_AMOUNT` double(10,3) DEFAULT NULL,
  `PAYMENT_AMOUNT` double(10,3) DEFAULT NULL,
  `COMMENTS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1002 DEFAULT CHARSET=utf8

CREATE TABLE `t_ledger_temp` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `RECEIPT_DATE` date DEFAULT NULL,
  `MEMBER_NAME` varchar(10) DEFAULT NULL,
  `CHECK_NUMBER` varchar(10) DEFAULT NULL,
  `CHECK_DATE` date DEFAULT NULL,
  `PAYMENT_TYPE` varchar(10) DEFAULT NULL,
  `DEPOSIT_AMOUNT` double(10,3) DEFAULT NULL,
  `PAYMENT_AMOUNT` double(10,3) DEFAULT NULL,
  `COMMENTS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1002 DEFAULT CHARSET=utf8

